### ISSUE TITLE
CPU frequency

### ISSUE THREAD

**Issue by Gplayjay** [project-sbc/Power-Control-Panel#5]
When I first boot up my gpd win 3 and have auto startup in the app it does not take the CPU frequency it usually requires me setting it 2 times for it to stick and I am on the latest version it happens when set manually as well from first boot every other time it seems to work only is an issue on first boot

**Comment by project-sbc** [comment]
Thanks i think I know the problem, I’ll fix in the next release

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Gplayjay ***@***.***>
Sent: Thursday, July 15, 2021 8:17:15 AM
To: project-sbc/Power-Control-Panel ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [project-sbc/Power-Control-Panel] CPU frequency (#5)


When I first boot up my gpd win 3 and have auto startup in the app it does not take the CPU frequency it usually requires me setting it 2 times for it to stick and I am on the latest version it happens when set manually as well from first boot every other time it seems to work only is an issue on first boot

**Comment by project-sbc** [comment]
Fixed, will be out in 0.2.6

**Comment by Gplayjay** [comment]
thank you so much i use it on my gpd win 3 and it makes everything so much
easier i really appreciate you staying by your word and fixing it by any
chance would you be able to fix an overlay that doesnt display mhz or would
you be able to tell me where to look to fix it its one of the ones in the
tools section on gpd win 3 discord the creator took down the broken one but
i still have the downloaded file

**Comment by project-sbc** [comment]
Will close as fixed in 0.2.6, which will release later today.

please reach out via discord about other issues not related to this app
